<?php

namespace Container9Skv7bx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RdW0Fn6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rdW0Fn6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rdW0Fn6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'qq' => ['privates', 'App\\Repository\\QuestionsRepository', 'getQuestionsRepositoryService', true],
            'qr' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
            're' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
            'rep' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'qq' => 'App\\Repository\\QuestionsRepository',
            'qr' => 'App\\Repository\\QuizRepository',
            're' => 'App\\Repository\\ReponseRepository',
            'rep' => 'App\\Repository\\ReclamationRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
