<?php

namespace Container9Skv7bx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hz0SbE2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hz0SbE2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hz0SbE2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'rep' => ['privates', 'App\\Repository\\QuestionsRepository', 'getQuestionsRepositoryService', true],
            'rr' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'paginator' => '?',
            'rep' => 'App\\Repository\\QuestionsRepository',
            'rr' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
