<?php

namespace Container9Skv7bx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7DaALADService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7DaALAD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7DaALAD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rep' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService', true],
            'request' => ['privates', '.errored..service_locator.7DaALAD.symfony\\Component\\HttpFoundation\\Request', NULL, 'Cannot autowire service ".service_locator.7DaALAD": it references class "symfony\\Component\\HttpFoundation\\Request" but no such service exists.'],
        ], [
            'rep' => 'App\\Repository\\NoteRepository',
            'request' => 'symfony\\Component\\HttpFoundation\\Request',
        ]);
    }
}
