<?php

namespace Container9Skv7bx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ap2cGkvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ap2cGkv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ap2cGkv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'request' => ['privates', '.errored..service_locator.ap2cGkv.symfony\\Component\\HttpFoundation\\Request', NULL, 'Cannot autowire service ".service_locator.ap2cGkv": it references class "symfony\\Component\\HttpFoundation\\Request" but no such service exists.'],
        ], [
            'em' => '?',
            'request' => 'symfony\\Component\\HttpFoundation\\Request',
        ]);
    }
}
