<?php

namespace Container9Skv7bx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ap2cGkv.symfony\Component\HttpFoundation\Request' shared service.
     *
     * @return \symfony\Component\HttpFoundation\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ap2cGkv": it references class "symfony\\Component\\HttpFoundation\\Request" but no such service exists.');
    }
}
