knp_paginator:
    page_range: 5                  # Number of pages displayed in the pagination menu
    default_options:
        page_name: page            # Name of the page parameter in the pagination links
        sort_field_name: sort      # Name of the sort field parameter in the pagination links
        sort_direction_name: direction # Name of the sort direction parameter in the pagination links
        distinct: true             # Whether to only count distinct results
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'  # Pagination template