<?php

namespace ContainerImuhCiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I0SVVJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i0S_vVJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i0S_vVJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repFormation' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
        ], [
            'repFormation' => 'App\\Repository\\FormationRepository',
        ]);
    }
}
