<?php

namespace ContainerImuhCiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YUlZ49KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YUlZ49K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YUlZ49K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repCategorie' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'repCategorie' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
