<?php

namespace ContainerImuhCiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSy8kFiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pSy8kFi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pSy8kFi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\CourFormationRepository', 'getCourFormationRepositoryService', true],
        ], [
            'manager' => '?',
            'repo' => 'App\\Repository\\CourFormationRepository',
        ]);
    }
}
