<?php

namespace ContainerImuhCiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nemk5D4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nemk5D4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nemk5D4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manger' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'manger' => '?',
            'repo' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
