<?php

namespace ContainerImuhCiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GLltxuCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gLltxuC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gLltxuC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repCours' => ['privates', 'App\\Repository\\CourFormationRepository', 'getCourFormationRepositoryService', true],
        ], [
            'repCours' => 'App\\Repository\\CourFormationRepository',
        ]);
    }
}
