#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
<<<<<<< HEAD
    controller: App\Controller\HomeController::home
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
=======
    controller: App\Controller\HomeController::home
>>>>>>> 8a5127b73af85eafd808d9a7d90dbf04c8bb4518
