<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \App\Entity\Formation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'idDeFormation', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'nomDeFormation', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'dateDeb', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'cout', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'nomCategorie'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'idDeFormation', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'nomDeFormation', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'dateDeb', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'cout', '' . "\0" . 'App\\Entity\\Formation' . "\0" . 'nomCategorie'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIidDeFormation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIidDeFormation', []);

        return parent::getIidDeFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function getnomDeFormation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getnomDeFormation', []);

        return parent::getnomDeFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setnomDeFormation(string $nomDeFormation): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setnomDeFormation', [$nomDeFormation]);

        return parent::setnomDeFormation($nomDeFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getduree(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getduree', []);

        return parent::getduree();
    }

    /**
     * {@inheritDoc}
     */
    public function setduree(string $duree): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setduree', [$duree]);

        return parent::setduree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(string $niveau): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getdateDeb(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getdateDeb', []);

        return parent::getdateDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setdateDeb(\DateTimeInterface $dateDeb): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setdateDeb', [$dateDeb]);

        return parent::setdateDeb($dateDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getdateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getdateFin', []);

        return parent::getdateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setdateFin(\DateTimeInterface $dateFin): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setdateFin', [$dateFin]);

        return parent::setdateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getcout(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcout', []);

        return parent::getcout();
    }

    /**
     * {@inheritDoc}
     */
    public function setcout(string $cout): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcout', [$cout]);

        return parent::setcout($cout);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCategorie(): ?\App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCategorie', []);

        return parent::getNomCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCategorie(?\App\Entity\Categorie $nomCategorie): \App\Entity\Formation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCategorie', [$nomCategorie]);

        return parent::setNomCategorie($nomCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\Categorie $categorie): \App\Entity\Formation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

}
