<?php

namespace ContainerPFxkepy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XzWNWjcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xzWNWjc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xzWNWjc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategorieController::AddCategorie' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CategorieController::AffichageCategorie' => ['privates', '.service_locator.YUlZ49K', 'get_ServiceLocator_YUlZ49KService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.Nemk5D4', 'get_ServiceLocator_Nemk5D4Service', true],
            'App\\Controller\\CategorieController::editAuthorAction' => ['privates', '.service_locator.gS71tbW', 'get_ServiceLocator_GS71tbWService', true],
            'App\\Controller\\CoursFormationController::AddCourFormation' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CoursFormationController::AffichageCours' => ['privates', '.service_locator.gLltxuC', 'get_ServiceLocator_GLltxuCService', true],
            'App\\Controller\\FormationController::AddFormation' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FormationController::AffichageFormation' => ['privates', '.service_locator.i0S_vVJ', 'get_ServiceLocator_I0SVVJService', true],
            'App\\Controller\\FormationController::delete' => ['privates', '.service_locator.E8pcLVk', 'get_ServiceLocator_E8pcLVkService', true],
            'App\\Controller\\FormationController::editAuthorAction' => ['privates', '.service_locator.E8pcLVk', 'get_ServiceLocator_E8pcLVkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CategorieController:AddCategorie' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CategorieController:AffichageCategorie' => ['privates', '.service_locator.YUlZ49K', 'get_ServiceLocator_YUlZ49KService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.Nemk5D4', 'get_ServiceLocator_Nemk5D4Service', true],
            'App\\Controller\\CategorieController:editAuthorAction' => ['privates', '.service_locator.gS71tbW', 'get_ServiceLocator_GS71tbWService', true],
            'App\\Controller\\CoursFormationController:AddCourFormation' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CoursFormationController:AffichageCours' => ['privates', '.service_locator.gLltxuC', 'get_ServiceLocator_GLltxuCService', true],
            'App\\Controller\\FormationController:AddFormation' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FormationController:AffichageFormation' => ['privates', '.service_locator.i0S_vVJ', 'get_ServiceLocator_I0SVVJService', true],
            'App\\Controller\\FormationController:delete' => ['privates', '.service_locator.E8pcLVk', 'get_ServiceLocator_E8pcLVkService', true],
            'App\\Controller\\FormationController:editAuthorAction' => ['privates', '.service_locator.E8pcLVk', 'get_ServiceLocator_E8pcLVkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CategorieController::AddCategorie' => '?',
            'App\\Controller\\CategorieController::AffichageCategorie' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::editAuthorAction' => '?',
            'App\\Controller\\CoursFormationController::AddCourFormation' => '?',
            'App\\Controller\\CoursFormationController::AffichageCours' => '?',
            'App\\Controller\\FormationController::AddFormation' => '?',
            'App\\Controller\\FormationController::AffichageFormation' => '?',
            'App\\Controller\\FormationController::delete' => '?',
            'App\\Controller\\FormationController::editAuthorAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategorieController:AddCategorie' => '?',
            'App\\Controller\\CategorieController:AffichageCategorie' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:editAuthorAction' => '?',
            'App\\Controller\\CoursFormationController:AddCourFormation' => '?',
            'App\\Controller\\CoursFormationController:AffichageCours' => '?',
            'App\\Controller\\FormationController:AddFormation' => '?',
            'App\\Controller\\FormationController:AffichageFormation' => '?',
            'App\\Controller\\FormationController:delete' => '?',
            'App\\Controller\\FormationController:editAuthorAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
