<?php

namespace ContainerSOKt1pM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B555RKgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B555RKg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B555RKg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CourFormationRepository' => ['privates', 'App\\Repository\\CourFormationRepository', 'getCourFormationRepositoryService', true],
        ], [
            'CourFormationRepository' => 'App\\Repository\\CourFormationRepository',
        ]);
    }
}
