<?php

namespace ContainerQY2NfaX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RuMECMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RuM_ECM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RuM_ECM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'r' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            're' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'r' => 'App\\Repository\\ReclamationRepository',
            're' => 'App\\Repository\\ReponseRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
