<?php

namespace ContainerQY2NfaX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6iKx16dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6iKx16d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6iKx16d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rep' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
            'reppp' => ['privates', 'App\\Repository\\QuestionsRepository', 'getQuestionsRepositoryService', true],
        ], [
            'rep' => 'App\\Repository\\QuizRepository',
            'reppp' => 'App\\Repository\\QuestionsRepository',
        ]);
    }
}
