<?php

namespace ContainerQY2NfaX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SFnOhXXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SFnOhXX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SFnOhXX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'r' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'rep' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
        ], [
            'r' => 'App\\Repository\\ReclamationRepository',
            'rep' => 'App\\Repository\\ReponseRepository',
        ]);
    }
}
