<?php

namespace ContainerQY2NfaX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Da_VWqMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.da.vWqM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.da.vWqM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'rep' => ['privates', 'App\\Repository\\QuestionsRepository', 'getQuestionsRepositoryService', true],
        ], [
            'paginator' => '?',
            'rep' => 'App\\Repository\\QuestionsRepository',
        ]);
    }
}
