#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app_chat:
    path: /chat
    controller: App\Controller\ChatController::chat
    methods: [GET, POST]