# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.autoload: 'C:\Users\Eya\projet\vendor\autoload.php'
    stripe_secret_key: 'sk_test_51P6dihBtpAjMlV8bUFIDKoPF9JdQFNc4qo6lM44lOrGMi0Iv9SdfAHu3B1J2tPB8wjshqhxiYKiIVCSRzcWTKshp00PEbveIOB'
    description_cours_directory: '%kernel.project_dir%/public/uploads'
    images_directory: '%kernel.project_dir%/public/uploads1/images'
    survey_monkey_access_token: '%env(SURVEY_MONKEY_ACCESS_TOKEN)%'
    facebook_page_access_token: '%env(FACEBOOK_PAGE_ACCESS_TOKEN)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    # Define the PDF generator service
    App\Service\PdfGeneratorService:
        public: true

    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Services are not public by default

    # Define the QR code builder service
    endroid.qr_code.builder:
        class: Endroid\QrCode\Builder\Builder

    Endroid\QrCode\Builder\BuilderInterface: '@endroid.qr_code.builder'

    # Define services in the App namespace
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
