<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBdOp1hC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBdOp1hC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBdOp1hC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBdOp1hC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBdOp1hC\App_KernelDevDebugContainer([
    'container.build_hash' => 'BdOp1hC',
    'container.build_id' => 'a611b792',
    'container.build_time' => 1715029738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBdOp1hC');
