<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9Skv7bx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9Skv7bx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9Skv7bx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9Skv7bx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9Skv7bx\App_KernelDevDebugContainer([
    'container.build_hash' => '9Skv7bx',
    'container.build_id' => 'c9f718e1',
    'container.build_time' => 1713862983,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9Skv7bx');
