<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEOLVATx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEOLVATx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEOLVATx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEOLVATx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEOLVATx\App_KernelDevDebugContainer([
    'container.build_hash' => 'EOLVATx',
    'container.build_id' => 'bf6a3c19',
    'container.build_time' => 1714068047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEOLVATx');
